name: $(version)-b$(BuildID)

trigger:
- development

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'Cynosura.Studio.CliTool/*.csproj'
    versioningScheme: 'off'
    buildProperties: 'PackageVersion=$(Build.BuildNumber)'
