version: '2.2'
services:
  web:
    environment:
      ASPNETCORE_URLS: 'http://+:5000'
      ConnectionStrings__DefaultConnection: 'Server=tcp:db,1433;Database=Cynosura.Studio;User ID=sa;Password=Qwerty123!;MultipleActiveResultSets=false'
      Jwt__CertificatePath: '/my/cert/mycert.pfx'
      Jwt__CertificatePassword: 'qwe123'
      Jwt__Authority: 'http://localhost:5000'
      Cors__Origin: http://localhost:5001
      Logging__LogLevel__Default: 'Trace'
    ports:
      - '0.0.0.0:5000:5000'
    volumes:
      - ./volumes/cert:/my/cert
      - logs:/my/logs
  webng:
    ports:
      - '0.0.0.0:5001:80'
    volumes:
      - ./volumes/webng/config.json:/usr/share/nginx/html/assets/config.json
  worker:
    environment:
      ConnectionStrings__DefaultConnection: 'Server=tcp:db,1433;Database=Cynosura.Studio;User ID=sa;Password=Qwerty123!;MultipleActiveResultSets=false'
      Logging__LogLevel__Default: 'Trace'
    volumes:
      - logs:/my/logs
  db:
    ports:
      - '0.0.0.0:1433:1433'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'Qwerty123!'
    volumes:
      - db:/var/opt/mssql
volumes:
  logs:
  db:
