version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Cynosura.Studio.Web/Dockerfile
    depends_on:
      - db
  webng:
    build:
      context: Cynosura.Studio.Web.Ng
  worker:
    build:
      context: .
      dockerfile: Cynosura.Studio.Worker/Dockerfile
    depends_on:
      - db
  db:
    image: 'mcr.microsoft.com/mssql/server:2017-latest-ubuntu'